# Generated by Django 4.0.8 on 2024-03-31 08:08

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_level_alter_course_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideo',
            name='video',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='course_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'wmv', '3gp', 'avi', 'mp3', 'mpeg'])]),
        ),
    ]
