# Generated by Django 4.0.8 on 2024-02-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_choice_id_alter_progress_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='single_attempt',
            field=models.BooleanField(default=True, help_text='If yes, only one attempt by a user will be permitted.', verbose_name='Single Attempt'),
        ),
    ]
