# Generated by Django 4.0.8 on 2024-03-31 08:08

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLecturerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lectures_list/', validators=[django.core.validators.FileExtensionValidator(['xls', 'xlsx'])])),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadStudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_list/', validators=[django.core.validators.FileExtensionValidator(['xls', 'xlsx'])])),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='default.png', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profile_pictures/%y/%m/%d/'),
        ),
    ]
